# The Fibonacci sequence is generated by taking two starting numbers,
# 1 and 1, and adding them together to get the next term (i.e., 1 + 1 = 2).
# Each subsequent term is calculated by adding together the two most
# recent terms (i.e., 1, 1, 2, we'd add together 1 + 2 = 3, so now 1, 1, 2, 3).

# Go through the terms of the Fibonacci sequence that are less than 4 million
# and find the even numbers.

# As a final answer, print out the sum (adding together) all of the numbers
# that you found were even in the Fibonacci sequence. See 'answers.txt' for
# how I expect your final output to be formatted.

# Tips:
# - Use a while loop to stop when your Fibonacci sequence terms get too large.
# - Use remainder to determine when a number is even.
# - Use two variables to hold your previous two terms and use a third temporary
#   variable when trying to add your new term and bumping out an old one.
